---
abstract: 'a POE Component that implements NSCA daemon functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-NSCA
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Server::NSCA:
    file: lib/POE/Component/Server/NSCA.pm
    version: 0.08
requires:
  Math::Random: 0.7
  Net::Netmask: 1.9015
  POE: 0.38
  POE::Component::Client::NSCA: 0.06
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
resources:
  homepage: http://github.com/bingos/poe-component-server-nsca/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-server-nsca.git
version: 0.08
