---
abstract: 'a POE Component that implements NSCA daemon functionality'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-NSCA
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  Math::Random: 0.7
  Net::Netmask: 1.9015
  POE: 0.38
  POE::Component::Client::NSCA: 0.06
  POE::Filter::Stream: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  Socket: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
